version: '3'

services:
  next-pages-app:
    container_name: next-pages-app
    build:
      dockerfile: Dockerfile.dev

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./next.config.js:/app/.next.config.js
      - ./styles:/app/styles
      - ./tailwind.config.js:/app/tailwind.config.js
    restart: always
    ports:
      - 3001:3000
