version: '3'

services:
  next-pages-app:
    container_name: next-pages-app
    build:
      dockerfile: Dockerfile.dev

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ./next.config.js:/app/.next.config.js
      - ./styles:/app/styles
      - ./tailwind.config.js:/app/tailwind.config.js
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true

